services:
  backing-tracking-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backing-tracking-web
    ports:
      - "8080:80"
    restart: unless-stopped

  backing-tracking-stemsplitter:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: backing-tracking-stemsplitter
    environment:
      CUSTOM_SONGS_ROOT: /data/custom-songs
      APP_DB_PATH: /data/app.db
    volumes:
      - ./api-data:/data
      - ./custom-songs:/data/custom-songs
    ports:
      - "4000:4000"
    restart: unless-stopped
